image: node:22
before_script:
  - npm install
pages:
  script:
    - npm run build
    - mv build/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
